/* Auto-generated by aspeed-data-gen. DO NOT EDIT. */
#ifndef ASPEED_AST2400_H
#define ASPEED_AST2400_H

#include <stdint.h>



typedef struct {
    volatile uint32_t CTRL; /* 0x0000: ColdFire Coprocessor Control Register (SCU100). Controls enable and reset of the ColdFire core.
 */
    volatile uint32_t SEG0_BASE; /* 0x0004: Segment 0 Base Register (SCU104). Maps ColdFire 0x000000–0x1FFFFF to a 2 MB-aligned BMC address.
 */
    volatile uint32_t SEG1_BASE; /* 0x0008: Segment 1 Base Register (SCU108). Maps ColdFire 0x200000–0x3FFFFF. */
    volatile uint32_t SEG2_BASE; /* 0x000c: Segment 2 Base Register (SCU10C). Maps ColdFire 0x400000–0x5FFFFF. */
    volatile uint32_t SEG3_BASE; /* 0x0010: Segment 3 Base Register (SCU110). Maps ColdFire 0x600000–0x7FFFFF. */
    volatile uint32_t SEG4_BASE; /* 0x0014: Segment 4 Base Register (SCU114). Maps ColdFire 0x800000–0x9FFFFF. */
} COPROC_V2_COPROCTypeDef;

/* Fieldset: coproc_v2::COPROC_CTRL */
#define COPROC_V2_COPROC_CTRL_EN_Pos 0
#define COPROC_V2_COPROC_CTRL_EN_Msk (1U << 0)
#define COPROC_V2_COPROC_CTRL_RESET_Pos 1
#define COPROC_V2_COPROC_CTRL_RESET_Msk (1U << 1)

/* Fieldset: coproc_v2::COPROC_SEG_BASE */
#define COPROC_V2_COPROC_SEG_BASE_BASE_Pos 21
#define COPROC_V2_COPROC_SEG_BASE_BASE_Msk (1023U << 21)
#define COPROC_V2_COPROC_SEG_BASE_ENDIAN_SWAP_Pos 31
#define COPROC_V2_COPROC_SEG_BASE_ENDIAN_SWAP_Msk (1U << 31)



typedef struct {
    volatile uint32_t IRQ_STATUS; /* 0x0000: IRQ Status Register (CVIC00). Read-only. Bit N = 1 when IRQ N is asserted and enabled (INT_ENABLE[N]=1). Masked view: software should read this to determine pending IRQs.
 */
    volatile uint8_t _pad0x08[4];
    volatile uint32_t RAW_STATUS; /* 0x0008: Raw Interrupt Status Register (CVIC08). Read-only. Bit N = 1 when IRQ N is asserted regardless of INT_ENABLE masking. Useful for debugging spurious interrupts.
 */
    volatile uint8_t _pad0x10[4];
    volatile uint32_t INT_ENABLE; /* 0x0010: Interrupt Enable Register (CVIC10). Read/write. Write 1 to enable the corresponding IRQ source. Write 0 to mask it.  Read returns the current enable state.
 */
    volatile uint32_t INT_ENABLE_CLR; /* 0x0014: Interrupt Enable Clear Register (CVIC14). Write-only. Write 1 to clear (mask) the corresponding IRQ source. Equivalent to writing 0 to INT_ENABLE[N] but without a read-modify-write.
 */
    volatile uint32_t SW_INT; /* 0x0018: Software Interrupt Register (CVIC18). Write-only. Write 1 to trigger a software-generated interrupt for the corresponding source. Used for inter-processor signalling and testing.
 */
    volatile uint32_t SW_INT_CLR; /* 0x001c: Software Interrupt Clear Register (CVIC1C). Write-only. Write 1 to clear a software-triggered interrupt.
 */
    volatile uint8_t _pad0x24[4];
    volatile uint32_t INT_SENSITIVITY; /* 0x0024: Interrupt Sensitivity Register (CVIC24). Read/write. Bit N = 0: level-triggered (default). Bit N = 1: edge-triggered. Must be configured before enabling the IRQ source.
 */
    volatile uint32_t BOTH_EDGE; /* 0x0028: Both-Edge Interrupt Register (CVIC28). Read/write. Valid only for edge-triggered sources (INT_SENSITIVITY[N]=1). Bit N = 1: trigger on both rising and falling edges. Bit N = 0: trigger on edge polarity set by INT_EVENT[N].
 */
    volatile uint32_t INT_EVENT; /* 0x002c: Interrupt Event Register (CVIC2C). Read/write. Bit N = 0: active-low / falling-edge trigger. Bit N = 1: active-high / rising-edge trigger. Ignored for sources with BOTH_EDGE[N]=1.
 */
    volatile uint8_t _pad0x38[8];
    volatile uint32_t EDGE_INT_CLR; /* 0x0038: Edge Interrupt Clear Register (CVIC38). Write-only. Write 1 to acknowledge and clear a latched edge interrupt. Has no effect on level-triggered sources.
 */
    volatile uint32_t EDGE_INT_STATUS; /* 0x003c: Edge Interrupt Status Register (CVIC3C). Read-only. Bit N = 1 when an edge has been latched for an edge-triggered source and has not yet been cleared via EDGE_INT_CLR.
 */
} CVIC_V1_CVICTypeDef;

/* Fieldset: cvic_v1::CVIC_IRQ32 */
#define CVIC_V1_CVIC_IRQ32_IRQ_Pos 0
#define CVIC_V1_CVIC_IRQ32_IRQ_Msk (4294967295U << 0)



typedef struct {
    volatile uint32_t G0_DATA; /* 0x0000: Group 0 (A/B/C/D) Data Value Register (GPIO000). */
    volatile uint32_t G0_DIR; /* 0x0004: Group 0 (A/B/C/D) Direction Register (GPIO004). 1=output. */
    volatile uint32_t G0_INT_EN; /* 0x0008: Group 0 (A/B/C/D) Interrupt Enable Register (GPIO008). */
    volatile uint32_t G0_INT_TYPE0; /* 0x000c: Group 0 Interrupt Sensitivity Type 0 (GPIO00C). */
    volatile uint32_t G0_INT_TYPE1; /* 0x0010: Group 0 Interrupt Sensitivity Type 1 (GPIO010). */
    volatile uint32_t G0_INT_TYPE2; /* 0x0014: Group 0 Interrupt Sensitivity Type 2 (GPIO014). */
    volatile uint32_t G0_INT_STATUS; /* 0x0018: Group 0 (A/B/C/D) Interrupt Status Register (GPIO018). RW1C. */
    volatile uint32_t G0_RESET_TOL; /* 0x001c: Group 0 WDT Reset Tolerant Register (GPIO01C). */
    volatile uint32_t G1_DATA; /* 0x0020: Group 1 (E/F/G/H) Data Value Register (GPIO020). */
    volatile uint32_t G1_DIR; /* 0x0024: Group 1 (E/F/G/H) Direction Register (GPIO024). */
    volatile uint32_t G1_INT_EN; /* 0x0028: Group 1 (E/F/G/H) Interrupt Enable Register (GPIO028). */
    volatile uint32_t G1_INT_TYPE0; /* 0x002c: Group 1 Interrupt Sensitivity Type 0 (GPIO02C). */
    volatile uint32_t G1_INT_TYPE1; /* 0x0030: Group 1 Interrupt Sensitivity Type 1 (GPIO030). */
    volatile uint32_t G1_INT_TYPE2; /* 0x0034: Group 1 Interrupt Sensitivity Type 2 (GPIO034). */
    volatile uint32_t G1_INT_STATUS; /* 0x0038: Group 1 (E/F/G/H) Interrupt Status Register (GPIO038). RW1C. */
    volatile uint32_t G1_RESET_TOL; /* 0x003c: Group 1 WDT Reset Tolerant Register (GPIO03C). */
    volatile uint8_t _pad0x60[32];
    volatile uint32_t G0_CMD_SRC0; /* 0x0060: Group 0 (A/B/C/D) Command Source Register 0 (GPIO060). Each bit is bit 0 of the 2-bit command source for that pin. {CMD_SRC1[n], CMD_SRC0[n]}: 0b00=ARM, 0b10=SSP.
 */
    volatile uint32_t G0_CMD_SRC1; /* 0x0064: Group 0 Command Source Register 1 (GPIO064). Bit 1 of each 2-bit source. */
    volatile uint32_t G1_CMD_SRC0; /* 0x0068: Group 1 (E/F/G/H) Command Source Register 0 (GPIO068). */
    volatile uint32_t G1_CMD_SRC1; /* 0x006c: Group 1 Command Source Register 1 (GPIO06C). */
    volatile uint32_t G2_DATA; /* 0x0070: Group 2 (I/J/K/L) Data Value Register (GPIO070). */
    volatile uint32_t G2_DIR; /* 0x0074: Group 2 (I/J/K/L) Direction Register (GPIO074). */
    volatile uint32_t G3_DATA; /* 0x0078: Group 3 (M/N/O/P) Data Value Register (GPIO078). */
    volatile uint32_t G3_DIR; /* 0x007c: Group 3 (M/N/O/P) Direction Register (GPIO07C). */
    volatile uint32_t G4_DATA; /* 0x0080: Group 4 (Q/R/S/T) Data Value Register (GPIO080). */
    volatile uint32_t G4_DIR; /* 0x0084: Group 4 (Q/R/S/T) Direction Register (GPIO084). */
    volatile uint32_t G5_DATA; /* 0x0088: Group 5 (U/V/W/X) Data Value Register (GPIO088). */
    volatile uint32_t G5_DIR; /* 0x008c: Group 5 (U/V/W/X) Direction Register (GPIO08C). */
    volatile uint32_t G2_CMD_SRC0; /* 0x0090: Group 2 (I/J/K/L) Command Source Register 0 (GPIO090). */
    volatile uint32_t G2_CMD_SRC1; /* 0x0094: Group 2 Command Source Register 1 (GPIO094). */
    volatile uint32_t G2_INT_EN; /* 0x0098: Group 2 (I/J/K/L) Interrupt Enable Register (GPIO098). */
    volatile uint32_t G2_INT_TYPE0; /* 0x009c: Group 2 Interrupt Sensitivity Type 0 (GPIO09C). */
    volatile uint32_t G2_INT_TYPE1; /* 0x00a0: Group 2 Interrupt Sensitivity Type 1 (GPIO0A0). */
    volatile uint32_t G2_INT_TYPE2; /* 0x00a4: Group 2 Interrupt Sensitivity Type 2 (GPIO0A4). */
    volatile uint32_t G2_INT_STATUS; /* 0x00a8: Group 2 (I/J/K/L) Interrupt Status Register (GPIO0A8). RW1C. */
    volatile uint32_t G2_RESET_TOL; /* 0x00ac: Group 2 WDT Reset Tolerant Register (GPIO0AC). */
    volatile uint8_t _pad0xb8[8];
    volatile uint32_t G2_INPUT_MASK; /* 0x00b8: Group 2 (I/J/K/L) Input Mask Register (GPIO0B8). */
    volatile uint8_t _pad0xc0[4];
    volatile uint32_t G0_DATA_READ; /* 0x00c0: Group 0 (A/B/C/D) Data Read Register (GPIO0C0). Input state. */
    volatile uint32_t G1_DATA_READ; /* 0x00c4: Group 1 (E/F/G/H) Data Read Register (GPIO0C4). */
    volatile uint32_t G2_DATA_READ; /* 0x00c8: Group 2 (I/J/K/L) Data Read Register (GPIO0C8). */
    volatile uint32_t G3_DATA_READ; /* 0x00cc: Group 3 (M/N/O/P) Data Read Register (GPIO0CC). */
    volatile uint32_t G4_DATA_READ; /* 0x00d0: Group 4 (Q/R/S/T) Data Read Register (GPIO0D0). */
    volatile uint32_t G5_DATA_READ; /* 0x00d4: Group 5 (U/V/W/X) Data Read Register (GPIO0D4). */
    volatile uint32_t G6_DATA_READ; /* 0x00d8: Group 6 (Y/Z) Data Read Register (GPIO0D8). Only bits [15:0] valid. */
    volatile uint8_t _pad0xe0[4];
    volatile uint32_t G3_CMD_SRC0; /* 0x00e0: Group 3 (M/N/O/P) Command Source Register 0 (GPIO0E0). */
    volatile uint32_t G3_CMD_SRC1; /* 0x00e4: Group 3 Command Source Register 1 (GPIO0E4). */
    volatile uint32_t G3_INT_EN; /* 0x00e8: Group 3 (M/N/O/P) Interrupt Enable Register (GPIO0E8). */
    volatile uint32_t G3_INT_TYPE0; /* 0x00ec: Group 3 Interrupt Sensitivity Type 0 (GPIO0EC). */
    volatile uint32_t G3_INT_TYPE1; /* 0x00f0: Group 3 Interrupt Sensitivity Type 1 (GPIO0F0). */
    volatile uint32_t G3_INT_TYPE2; /* 0x00f4: Group 3 Interrupt Sensitivity Type 2 (GPIO0F4). */
    volatile uint32_t G3_INT_STATUS; /* 0x00f8: Group 3 (M/N/O/P) Interrupt Status Register (GPIO0F8). RW1C. */
    volatile uint32_t G3_RESET_TOL; /* 0x00fc: Group 3 WDT Reset Tolerant Register (GPIO0FC). */
    volatile uint8_t _pad0x108[8];
    volatile uint32_t G3_INPUT_MASK; /* 0x0108: Group 3 (M/N/O/P) Input Mask Register (GPIO108). */
    volatile uint8_t _pad0x110[4];
    volatile uint32_t G4_CMD_SRC0; /* 0x0110: Group 4 (Q/R/S/T) Command Source Register 0 (GPIO110). */
    volatile uint32_t G4_CMD_SRC1; /* 0x0114: Group 4 Command Source Register 1 (GPIO114). */
    volatile uint32_t G4_INT_EN; /* 0x0118: Group 4 (Q/R/S/T) Interrupt Enable Register (GPIO118). */
    volatile uint32_t G4_INT_TYPE0; /* 0x011c: Group 4 Interrupt Sensitivity Type 0 (GPIO11C). */
    volatile uint32_t G4_INT_TYPE1; /* 0x0120: Group 4 Interrupt Sensitivity Type 1 (GPIO120). */
    volatile uint32_t G4_INT_TYPE2; /* 0x0124: Group 4 Interrupt Sensitivity Type 2 (GPIO124). */
    volatile uint32_t G4_INT_STATUS; /* 0x0128: Group 4 (Q/R/S/T) Interrupt Status Register (GPIO128). RW1C. */
    volatile uint32_t G4_RESET_TOL; /* 0x012c: Group 4 WDT Reset Tolerant Register (GPIO12C). */
    volatile uint8_t _pad0x138[8];
    volatile uint32_t G4_INPUT_MASK; /* 0x0138: Group 4 (Q/R/S/T) Input Mask Register (GPIO138). */
    volatile uint8_t _pad0x140[4];
    volatile uint32_t G5_CMD_SRC0; /* 0x0140: Group 5 (U/V/W/X) Command Source Register 0 (GPIO140). */
    volatile uint32_t G5_CMD_SRC1; /* 0x0144: Group 5 Command Source Register 1 (GPIO144). */
    volatile uint32_t G5_INT_EN; /* 0x0148: Group 5 (U/V/W/X) Interrupt Enable Register (GPIO148). */
    volatile uint32_t G5_INT_TYPE0; /* 0x014c: Group 5 Interrupt Sensitivity Type 0 (GPIO14C). */
    volatile uint32_t G5_INT_TYPE1; /* 0x0150: Group 5 Interrupt Sensitivity Type 1 (GPIO150). */
    volatile uint32_t G5_INT_TYPE2; /* 0x0154: Group 5 Interrupt Sensitivity Type 2 (GPIO154). */
    volatile uint32_t G5_INT_STATUS; /* 0x0158: Group 5 (U/V/W/X) Interrupt Status Register (GPIO158). RW1C. */
    volatile uint32_t G5_RESET_TOL; /* 0x015c: Group 5 WDT Reset Tolerant Register (GPIO15C). */
    volatile uint8_t _pad0x168[8];
    volatile uint32_t G5_INPUT_MASK; /* 0x0168: Group 5 (U/V/W/X) Input Mask Register (GPIO168). */
    volatile uint8_t _pad0x170[4];
    volatile uint32_t G6_CMD_SRC0; /* 0x0170: Group 6 (Y/Z) Command Source Register 0 (GPIO170). */
    volatile uint32_t G6_CMD_SRC1; /* 0x0174: Group 6 Command Source Register 1 (GPIO174). */
    volatile uint32_t G6_INT_EN; /* 0x0178: Group 6 (Y/Z) Interrupt Enable Register (GPIO178). */
    volatile uint32_t G6_INT_TYPE0; /* 0x017c: Group 6 Interrupt Sensitivity Type 0 (GPIO17C). */
    volatile uint32_t G6_INT_TYPE1; /* 0x0180: Group 6 Interrupt Sensitivity Type 1 (GPIO180). */
    volatile uint32_t G6_INT_TYPE2; /* 0x0184: Group 6 Interrupt Sensitivity Type 2 (GPIO184). */
    volatile uint32_t G6_INT_STATUS; /* 0x0188: Group 6 (Y/Z) Interrupt Status Register (GPIO188). RW1C. */
    volatile uint32_t G6_RESET_TOL; /* 0x018c: Group 6 WDT Reset Tolerant Register (GPIO18C). */
    volatile uint8_t _pad0x198[8];
    volatile uint32_t G6_INPUT_MASK; /* 0x0198: Group 6 (Y/Z) Input Mask Register (GPIO198). */
    volatile uint8_t _pad0x1d0[52];
    volatile uint32_t G0_INPUT_MASK; /* 0x01d0: Group 0 (A/B/C/D) Input Mask Register (GPIO1D0). */
    volatile uint32_t G1_INPUT_MASK; /* 0x01d4: Group 1 (E/F/G/H) Input Mask Register (GPIO1D4). */
    volatile uint8_t _pad0x1e0[8];
    volatile uint32_t G6_DATA; /* 0x01e0: Group 6 (Y/Z) Data Value Register (GPIO1E0). Only bits [15:0] valid. */
    volatile uint32_t G6_DIR; /* 0x01e4: Group 6 (Y/Z) Direction Register (GPIO1E4). */
    volatile uint8_t _pad0x2ac[196];
    volatile uint32_t INDEX; /* 0x02ac: GPIO Index Register (GPIO2AC). Command-based interface for per-pin configuration. bits [7:0]   = pin number (0–207) bit  [12]    = command (0=write, 1=read) bits [19:16] = type (0=DATA, 1=DIR, 2=INTERRUPT, 3=DEBOUNCE,
                     4=TOLERANCE, 5=CMD_SRC, 6=INPUT_MASK)
bits [24:20] = data (for INTERRUPT: bit0=int_enable,
                     bits[4:1]=int_type 0=FALL 1=RISE 2=LOW 3=HIGH 4=BOTH)
 */
    volatile uint8_t _pad0x2d0[32];
    volatile uint32_t CMD_SRC_SEL; /* 0x02d0: GPIO Command Source Selection Register (GPIO2D0). Assigns a bus master index to each of the 5 master slots. SSP master number = 6 (ASPEED_GPIO_SEL_SSP). Configure to allow SSP to write GPIO via CMD_SRC registers.
 */
} GPIO_V1_GPIOTypeDef;

/* Fieldset: gpio_v1::GPIO32 */
#define GPIO_V1_GPIO32_PINS_Pos 0
#define GPIO_V1_GPIO32_PINS_Msk (4294967295U << 0)

/* Fieldset: gpio_v1::GPIO_INDEX */
#define GPIO_V1_GPIO_INDEX_INDEX_NUMBER_Pos 0
#define GPIO_V1_GPIO_INDEX_INDEX_NUMBER_Msk (255U << 0)
#define GPIO_V1_GPIO_INDEX_INDEX_CMD_Pos 12
#define GPIO_V1_GPIO_INDEX_INDEX_CMD_Msk (1U << 12)
#define GPIO_V1_GPIO_INDEX_INDEX_TYPE_Pos 16
#define GPIO_V1_GPIO_INDEX_INDEX_TYPE_Msk (15U << 16)
#define GPIO_V1_GPIO_INDEX_INDEX_DATA_Pos 20
#define GPIO_V1_GPIO_INDEX_INDEX_DATA_Msk (31U << 20)

/* Fieldset: gpio_v1::GPIO_CMD_SRC_SEL */
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST1_Pos 0
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST1_Msk (31U << 0)
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST2_Pos 5
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST2_Msk (31U << 5)
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST3_Pos 10
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST3_Msk (31U << 10)
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST4_Pos 15
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST4_Msk (31U << 15)
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST5_Pos 20
#define GPIO_V1_GPIO_CMD_SRC_SEL_MST5_Msk (31U << 20)
#define GPIO_V1_GPIO_CMD_SRC_SEL_LOCK_Pos 31
#define GPIO_V1_GPIO_CMD_SRC_SEL_LOCK_Msk (1U << 31)



typedef struct {
    volatile uint32_t T1_STATUS; /* 0x0000: Timer 1 Counter Status (TMC00). Read-only current count. */
    volatile uint32_t T1_RELOAD; /* 0x0004: Timer 1 Reload Value (TMC04). Loaded on enable or overflow. */
    volatile uint32_t T1_MATCH1; /* 0x0008: Timer 1 First Match Register (TMC08). */
    volatile uint8_t _pad0x10[4];
    volatile uint32_t T2_STATUS; /* 0x0010: Timer 2 Counter Status (TMC10). */
    volatile uint32_t T2_RELOAD; /* 0x0014: Timer 2 Reload Value (TMC14). */
    volatile uint32_t T2_MATCH1; /* 0x0018: Timer 2 First Match Register (TMC18). */
    volatile uint8_t _pad0x20[4];
    volatile uint32_t T3_STATUS; /* 0x0020: Timer 3 Counter Status (TMC20). */
    volatile uint32_t T3_RELOAD; /* 0x0024: Timer 3 Reload Value (TMC24). */
    volatile uint32_t T3_MATCH1; /* 0x0028: Timer 3 First Match Register (TMC28). */
    volatile uint8_t _pad0x30[4];
    volatile uint32_t CTRL; /* 0x0030: Global Timer Control Register (TMC30). Write 1 to set specific bits; write 1 to TMC3C to clear. 4 bits per timer: [WDT_EN, OVF_INTR, CLK_SEL, EN], timer 1 in bits [3:0].
 */
    volatile uint32_t INT_STATUS; /* 0x0034: Timer Interrupt Status Register (TMC34). RW1C. Bit N-1 set when timer N overflows and OVF_INTR is enabled. Clear by writing 1 to the bit.
 */
    volatile uint8_t _pad0x3c[4];
    volatile uint32_t CTRL_CLR; /* 0x003c: TMC30 Clear Register (TMC3C). Write-only. Write 1 to a bit to clear the same bit in CTRL (TMC30).
 */
    volatile uint32_t T4_STATUS; /* 0x0040: Timer 4 Counter Status (TMC40). */
    volatile uint32_t T4_RELOAD; /* 0x0044: Timer 4 Reload Value (TMC44). */
    volatile uint32_t T4_MATCH1; /* 0x0048: Timer 4 First Match Register (TMC48). */
    volatile uint8_t _pad0x50[4];
    volatile uint32_t T5_STATUS; /* 0x0050: Timer 5 Counter Status (TMC50). */
    volatile uint32_t T5_RELOAD; /* 0x0054: Timer 5 Reload Value (TMC54). */
    volatile uint32_t T5_MATCH1; /* 0x0058: Timer 5 First Match Register (TMC58). */
    volatile uint8_t _pad0x60[4];
    volatile uint32_t T6_STATUS; /* 0x0060: Timer 6 Counter Status (TMC60). */
    volatile uint32_t T6_RELOAD; /* 0x0064: Timer 6 Reload Value (TMC64). */
    volatile uint32_t T6_MATCH1; /* 0x0068: Timer 6 First Match Register (TMC68). */
    volatile uint8_t _pad0x70[4];
    volatile uint32_t T7_STATUS; /* 0x0070: Timer 7 Counter Status (TMC70). */
    volatile uint32_t T7_RELOAD; /* 0x0074: Timer 7 Reload Value (TMC74). */
    volatile uint32_t T7_MATCH1; /* 0x0078: Timer 7 First Match Register (TMC78). */
    volatile uint8_t _pad0x80[4];
    volatile uint32_t T8_STATUS; /* 0x0080: Timer 8 Counter Status (TMC80). */
    volatile uint32_t T8_RELOAD; /* 0x0084: Timer 8 Reload Value (TMC84). */
    volatile uint32_t T8_MATCH1; /* 0x0088: Timer 8 First Match Register (TMC88). */
} TIMER_V1_TIMERTypeDef;

/* Fieldset: timer_v1::TMC_COUNTER */
#define TIMER_V1_TMC_COUNTER_VALUE_Pos 0
#define TIMER_V1_TMC_COUNTER_VALUE_Msk (4294967295U << 0)

/* Fieldset: timer_v1::TMC_CTRL */
#define TIMER_V1_TMC_CTRL_T1_EN_Pos 0
#define TIMER_V1_TMC_CTRL_T1_EN_Msk (1U << 0)
#define TIMER_V1_TMC_CTRL_T1_CLK_SEL_Pos 1
#define TIMER_V1_TMC_CTRL_T1_CLK_SEL_Msk (1U << 1)
#define TIMER_V1_TMC_CTRL_T1_OVF_INTR_Pos 2
#define TIMER_V1_TMC_CTRL_T1_OVF_INTR_Msk (1U << 2)
#define TIMER_V1_TMC_CTRL_T1_WDT_EN_Pos 3
#define TIMER_V1_TMC_CTRL_T1_WDT_EN_Msk (1U << 3)
#define TIMER_V1_TMC_CTRL_T2_EN_Pos 4
#define TIMER_V1_TMC_CTRL_T2_EN_Msk (1U << 4)
#define TIMER_V1_TMC_CTRL_T2_CLK_SEL_Pos 5
#define TIMER_V1_TMC_CTRL_T2_CLK_SEL_Msk (1U << 5)
#define TIMER_V1_TMC_CTRL_T2_OVF_INTR_Pos 6
#define TIMER_V1_TMC_CTRL_T2_OVF_INTR_Msk (1U << 6)
#define TIMER_V1_TMC_CTRL_T2_WDT_EN_Pos 7
#define TIMER_V1_TMC_CTRL_T2_WDT_EN_Msk (1U << 7)
#define TIMER_V1_TMC_CTRL_T3_EN_Pos 8
#define TIMER_V1_TMC_CTRL_T3_EN_Msk (1U << 8)
#define TIMER_V1_TMC_CTRL_T3_CLK_SEL_Pos 9
#define TIMER_V1_TMC_CTRL_T3_CLK_SEL_Msk (1U << 9)
#define TIMER_V1_TMC_CTRL_T3_OVF_INTR_Pos 10
#define TIMER_V1_TMC_CTRL_T3_OVF_INTR_Msk (1U << 10)
#define TIMER_V1_TMC_CTRL_T3_WDT_EN_Pos 11
#define TIMER_V1_TMC_CTRL_T3_WDT_EN_Msk (1U << 11)
#define TIMER_V1_TMC_CTRL_T4_EN_Pos 12
#define TIMER_V1_TMC_CTRL_T4_EN_Msk (1U << 12)
#define TIMER_V1_TMC_CTRL_T4_CLK_SEL_Pos 13
#define TIMER_V1_TMC_CTRL_T4_CLK_SEL_Msk (1U << 13)
#define TIMER_V1_TMC_CTRL_T4_OVF_INTR_Pos 14
#define TIMER_V1_TMC_CTRL_T4_OVF_INTR_Msk (1U << 14)
#define TIMER_V1_TMC_CTRL_T4_WDT_EN_Pos 15
#define TIMER_V1_TMC_CTRL_T4_WDT_EN_Msk (1U << 15)
#define TIMER_V1_TMC_CTRL_T5_EN_Pos 16
#define TIMER_V1_TMC_CTRL_T5_EN_Msk (1U << 16)
#define TIMER_V1_TMC_CTRL_T5_CLK_SEL_Pos 17
#define TIMER_V1_TMC_CTRL_T5_CLK_SEL_Msk (1U << 17)
#define TIMER_V1_TMC_CTRL_T5_OVF_INTR_Pos 18
#define TIMER_V1_TMC_CTRL_T5_OVF_INTR_Msk (1U << 18)
#define TIMER_V1_TMC_CTRL_T5_WDT_EN_Pos 19
#define TIMER_V1_TMC_CTRL_T5_WDT_EN_Msk (1U << 19)
#define TIMER_V1_TMC_CTRL_T6_EN_Pos 20
#define TIMER_V1_TMC_CTRL_T6_EN_Msk (1U << 20)
#define TIMER_V1_TMC_CTRL_T6_CLK_SEL_Pos 21
#define TIMER_V1_TMC_CTRL_T6_CLK_SEL_Msk (1U << 21)
#define TIMER_V1_TMC_CTRL_T6_OVF_INTR_Pos 22
#define TIMER_V1_TMC_CTRL_T6_OVF_INTR_Msk (1U << 22)
#define TIMER_V1_TMC_CTRL_T6_WDT_EN_Pos 23
#define TIMER_V1_TMC_CTRL_T6_WDT_EN_Msk (1U << 23)
#define TIMER_V1_TMC_CTRL_T7_EN_Pos 24
#define TIMER_V1_TMC_CTRL_T7_EN_Msk (1U << 24)
#define TIMER_V1_TMC_CTRL_T7_CLK_SEL_Pos 25
#define TIMER_V1_TMC_CTRL_T7_CLK_SEL_Msk (1U << 25)
#define TIMER_V1_TMC_CTRL_T7_OVF_INTR_Pos 26
#define TIMER_V1_TMC_CTRL_T7_OVF_INTR_Msk (1U << 26)
#define TIMER_V1_TMC_CTRL_T7_WDT_EN_Pos 27
#define TIMER_V1_TMC_CTRL_T7_WDT_EN_Msk (1U << 27)
#define TIMER_V1_TMC_CTRL_T8_EN_Pos 28
#define TIMER_V1_TMC_CTRL_T8_EN_Msk (1U << 28)
#define TIMER_V1_TMC_CTRL_T8_CLK_SEL_Pos 29
#define TIMER_V1_TMC_CTRL_T8_CLK_SEL_Msk (1U << 29)
#define TIMER_V1_TMC_CTRL_T8_OVF_INTR_Pos 30
#define TIMER_V1_TMC_CTRL_T8_OVF_INTR_Msk (1U << 30)
#define TIMER_V1_TMC_CTRL_T8_WDT_EN_Pos 31
#define TIMER_V1_TMC_CTRL_T8_WDT_EN_Msk (1U << 31)

/* Fieldset: timer_v1::TMC_INT_STATUS */
#define TIMER_V1_TMC_INT_STATUS_T1_INT_Pos 0
#define TIMER_V1_TMC_INT_STATUS_T1_INT_Msk (1U << 0)
#define TIMER_V1_TMC_INT_STATUS_T2_INT_Pos 1
#define TIMER_V1_TMC_INT_STATUS_T2_INT_Msk (1U << 1)
#define TIMER_V1_TMC_INT_STATUS_T3_INT_Pos 2
#define TIMER_V1_TMC_INT_STATUS_T3_INT_Msk (1U << 2)
#define TIMER_V1_TMC_INT_STATUS_T4_INT_Pos 3
#define TIMER_V1_TMC_INT_STATUS_T4_INT_Msk (1U << 3)
#define TIMER_V1_TMC_INT_STATUS_T5_INT_Pos 4
#define TIMER_V1_TMC_INT_STATUS_T5_INT_Msk (1U << 4)
#define TIMER_V1_TMC_INT_STATUS_T6_INT_Pos 5
#define TIMER_V1_TMC_INT_STATUS_T6_INT_Msk (1U << 5)
#define TIMER_V1_TMC_INT_STATUS_T7_INT_Pos 6
#define TIMER_V1_TMC_INT_STATUS_T7_INT_Msk (1U << 6)
#define TIMER_V1_TMC_INT_STATUS_T8_INT_Pos 7
#define TIMER_V1_TMC_INT_STATUS_T8_INT_Msk (1U << 7)



typedef struct {
    volatile uint32_t RBR_THR; /* 0x0000: Receiver Buffer Register (read, DLAB=0) / Transmit Holding Register (write, DLAB=0) / Baud Divisor Low byte (DLAB=1). Read: received byte.  Write: byte to transmit. DLAB=1 access handled in HAL code via raw pointer.
 */
    volatile uint32_t IER; /* 0x0004: Interrupt Enable Register (DLAB=0) / Baud Divisor High byte (DLAB=1). DLAB=1 access handled in HAL code via raw pointer.
 */
    volatile uint32_t FCR_IIR; /* 0x0008: FIFO Control Register (write) / Interrupt Identification Register (read). Reads return IIR; writes configure FIFO via FCR fields. FCR is write-only; IIR is read-only.
 */
    volatile uint32_t LCR; /* 0x000c: Line Control Register. Controls data format and DLAB. */
    volatile uint32_t MCR; /* 0x0010: Modem Control Register. */
    volatile uint32_t LSR; /* 0x0014: Line Status Register. TX/RX status flags. */
    volatile uint32_t MSR; /* 0x0018: Modem Status Register. */
    volatile uint32_t SCR; /* 0x001c: Scratch Register. Read/write with no hardware effect. */
} UART_V1_UARTTypeDef;

/* Fieldset: uart_v1::DATA8 */
#define UART_V1_DATA8_DATA_Pos 0
#define UART_V1_DATA8_DATA_Msk (255U << 0)

/* Fieldset: uart_v1::IER */
#define UART_V1_IER_ERBFI_Pos 0
#define UART_V1_IER_ERBFI_Msk (1U << 0)
#define UART_V1_IER_ETBEI_Pos 1
#define UART_V1_IER_ETBEI_Msk (1U << 1)
#define UART_V1_IER_ELSI_Pos 2
#define UART_V1_IER_ELSI_Msk (1U << 2)
#define UART_V1_IER_EDSSI_Pos 3
#define UART_V1_IER_EDSSI_Msk (1U << 3)

/* Fieldset: uart_v1::FCR_IIR */
#define UART_V1_FCR_IIR_FIFOE_OR_IP_Pos 0
#define UART_V1_FCR_IIR_FIFOE_OR_IP_Msk (1U << 0)
#define UART_V1_FCR_IIR_RFIFOR_OR_IID1_Pos 1
#define UART_V1_FCR_IIR_RFIFOR_OR_IID1_Msk (1U << 1)
#define UART_V1_FCR_IIR_XFIFOR_OR_IID2_Pos 2
#define UART_V1_FCR_IIR_XFIFOR_OR_IID2_Msk (1U << 2)
#define UART_V1_FCR_IIR_DMA_OR_IID3_Pos 3
#define UART_V1_FCR_IIR_DMA_OR_IID3_Msk (1U << 3)
#define UART_V1_FCR_IIR_TX_TRIG_Pos 4
#define UART_V1_FCR_IIR_TX_TRIG_Msk (3U << 4)
#define UART_V1_FCR_IIR_RX_TRIG_Pos 6
#define UART_V1_FCR_IIR_RX_TRIG_Msk (3U << 6)

/* Fieldset: uart_v1::LCR */
#define UART_V1_LCR_WLS_Pos 0
#define UART_V1_LCR_WLS_Msk (3U << 0)
#define UART_V1_LCR_STB_Pos 2
#define UART_V1_LCR_STB_Msk (1U << 2)
#define UART_V1_LCR_PEN_Pos 3
#define UART_V1_LCR_PEN_Msk (1U << 3)
#define UART_V1_LCR_EPS_Pos 4
#define UART_V1_LCR_EPS_Msk (1U << 4)
#define UART_V1_LCR_SP_Pos 5
#define UART_V1_LCR_SP_Msk (1U << 5)
#define UART_V1_LCR_BC_Pos 6
#define UART_V1_LCR_BC_Msk (1U << 6)
#define UART_V1_LCR_DLAB_Pos 7
#define UART_V1_LCR_DLAB_Msk (1U << 7)

/* Fieldset: uart_v1::MCR */
#define UART_V1_MCR_DTR_Pos 0
#define UART_V1_MCR_DTR_Msk (1U << 0)
#define UART_V1_MCR_RTS_Pos 1
#define UART_V1_MCR_RTS_Msk (1U << 1)
#define UART_V1_MCR_OUT1_Pos 2
#define UART_V1_MCR_OUT1_Msk (1U << 2)
#define UART_V1_MCR_OUT2_Pos 3
#define UART_V1_MCR_OUT2_Msk (1U << 3)
#define UART_V1_MCR_LOOP_Pos 4
#define UART_V1_MCR_LOOP_Msk (1U << 4)

/* Fieldset: uart_v1::LSR */
#define UART_V1_LSR_DR_Pos 0
#define UART_V1_LSR_DR_Msk (1U << 0)
#define UART_V1_LSR_OE_Pos 1
#define UART_V1_LSR_OE_Msk (1U << 1)
#define UART_V1_LSR_PE_Pos 2
#define UART_V1_LSR_PE_Msk (1U << 2)
#define UART_V1_LSR_FE_Pos 3
#define UART_V1_LSR_FE_Msk (1U << 3)
#define UART_V1_LSR_BI_Pos 4
#define UART_V1_LSR_BI_Msk (1U << 4)
#define UART_V1_LSR_THRE_Pos 5
#define UART_V1_LSR_THRE_Msk (1U << 5)
#define UART_V1_LSR_TEMT_Pos 6
#define UART_V1_LSR_TEMT_Msk (1U << 6)
#define UART_V1_LSR_FIFOERR_Pos 7
#define UART_V1_LSR_FIFOERR_Msk (1U << 7)

/* Fieldset: uart_v1::MSR */
#define UART_V1_MSR_DCTS_Pos 0
#define UART_V1_MSR_DCTS_Msk (1U << 0)
#define UART_V1_MSR_DDSR_Pos 1
#define UART_V1_MSR_DDSR_Msk (1U << 1)
#define UART_V1_MSR_TERI_Pos 2
#define UART_V1_MSR_TERI_Msk (1U << 2)
#define UART_V1_MSR_DDCD_Pos 3
#define UART_V1_MSR_DDCD_Msk (1U << 3)
#define UART_V1_MSR_CTS_Pos 4
#define UART_V1_MSR_CTS_Msk (1U << 4)
#define UART_V1_MSR_DSR_Pos 5
#define UART_V1_MSR_DSR_Msk (1U << 5)
#define UART_V1_MSR_RI_Pos 6
#define UART_V1_MSR_RI_Msk (1U << 6)
#define UART_V1_MSR_DCD_Pos 7
#define UART_V1_MSR_DCD_Msk (1U << 7)



typedef struct {
    volatile uint32_t STATUS; /* 0x0000: Counter Status Register (WDT00). Read-only. Current down-counter value in microseconds. Loaded from RELOAD on reset or restart (0x4755 write to RESTART). Counts down to 0 when WDT is enabled. Default / power-on value: 0x014F_B180 (~22 s).
 */
    volatile uint32_t RELOAD; /* 0x0004: Counter Reload Value Register (WDT04). Value loaded into STATUS on reset or when 0x4755 is written to the RESTART register.  Units: microseconds. Default: 0x014F_B180 (~22 s).
 */
    volatile uint32_t RESTART; /* 0x0008: Counter Restart Register (WDT08). Write-only trigger. Write 0x4755 to reload STATUS from RELOAD and restart the counter (provided CTRL.WDT_EN=1).  Any other write value is ignored.
 */
    volatile uint32_t CTRL; /* 0x000c: Control Register (WDT0C). Configures reset mode, interrupt, and enable. Default: 0x0010 (WDT_EN=0, RST_SYS=1 = SOC reset mode).
 */
    volatile uint8_t _pad0x24[20];
    volatile uint32_t SW_RESET_CTRL; /* 0x0024: Software Mode Reset Control Register (WDT24). Write 0xAEED_F123 to trigger an immediate software-mode SOC reset (after setting SW_RESET_MASK1 to select which blocks to reset). This bit clears automatically after reset.
 */
    volatile uint32_t SW_RESET_MASK1; /* 0x0028: Software Mode Reset Mask Register #1 (WDT28). Each bit enables the corresponding subsystem to be reset when SW_RESET_CTRL is triggered. Zephyr uses 0x3FFF_FF1 to reset most subsystems.
 */
} WDT_V1_WDTTypeDef;

/* Fieldset: wdt_v1::WDT_COUNTER */
#define WDT_V1_WDT_COUNTER_VALUE_Pos 0
#define WDT_V1_WDT_COUNTER_VALUE_Msk (4294967295U << 0)

/* Fieldset: wdt_v1::WDT_RESTART */
#define WDT_V1_WDT_RESTART_KEY_Pos 0
#define WDT_V1_WDT_RESTART_KEY_Msk (65535U << 0)

/* Fieldset: wdt_v1::WDT_CTRL */
#define WDT_V1_WDT_CTRL_WDT_EN_Pos 0
#define WDT_V1_WDT_CTRL_WDT_EN_Msk (1U << 0)
#define WDT_V1_WDT_CTRL_RST_SYS_Pos 1
#define WDT_V1_WDT_CTRL_RST_SYS_Msk (1U << 1)
#define WDT_V1_WDT_CTRL_WDT_RESET_BY_SOC_Pos 4
#define WDT_V1_WDT_CTRL_WDT_RESET_BY_SOC_Msk (1U << 4)
#define WDT_V1_WDT_CTRL_RST_MODE_Pos 5
#define WDT_V1_WDT_CTRL_RST_MODE_Msk (3U << 5)
#define WDT_V1_WDT_CTRL_WDT_EXT_Pos 27
#define WDT_V1_WDT_CTRL_WDT_EXT_Msk (1U << 27)
#define WDT_V1_WDT_CTRL_WDT_INTR_Pos 28
#define WDT_V1_WDT_CTRL_WDT_INTR_Msk (1U << 28)

/* Fieldset: wdt_v1::WDT_SW_RESET_CTRL */
#define WDT_V1_WDT_SW_RESET_CTRL_TRIGGER_Pos 0
#define WDT_V1_WDT_SW_RESET_CTRL_TRIGGER_Msk (4294967295U << 0)

/* Fieldset: wdt_v1::WDT_SW_RESET_MASK1 */
#define WDT_V1_WDT_SW_RESET_MASK1_MASK_Pos 0
#define WDT_V1_WDT_SW_RESET_MASK1_MASK_Msk (4294967295U << 0)



/* Peripheral instances */
/* ColdFire coprocessor control (SCU100–SCU114): 5 segments × 2 MB */
#define COPROC_BASE (0x002e2100U)
#define COPROC ((COPROC_V2_COPROCTypeDef *)COPROC_BASE)
/* ColdFire VIC: 32 IRQ sources (same IP as AST2500) */
#define CVIC_BASE (0x002c2000U)
#define CVIC ((CVIC_V1_CVICTypeDef *)CVIC_BASE)
/* UART1 (16550, 4-byte stride) */
#define UART1_BASE (0x00683000U)
#define UART1 ((UART_V1_UARTTypeDef *)UART1_BASE)
/* UART2 (16550, 4-byte stride) */
#define UART2_BASE (0x0068d000U)
#define UART2 ((UART_V1_UARTTypeDef *)UART2_BASE)
/* UART3 (16550, 4-byte stride) */
#define UART3_BASE (0x0068e000U)
#define UART3 ((UART_V1_UARTTypeDef *)UART3_BASE)
/* UART4 (16550, 4-byte stride) */
#define UART4_BASE (0x0068f000U)
#define UART4 ((UART_V1_UARTTypeDef *)UART4_BASE)
/* UART5 (16550, 4-byte stride) */
#define UART5_BASE (0x00684000U)
#define UART5 ((UART_V1_UARTTypeDef *)UART5_BASE)
/* Hardware timer (8 × 32-bit countdown) */
#define TIMER_BASE (0x00682000U)
#define TIMER ((TIMER_V1_TIMERTypeDef *)TIMER_BASE)
/* Watchdog timer 0 (same IP as AST2500) */
#define WDT_BASE (0x00685000U)
#define WDT ((WDT_V1_WDTTypeDef *)WDT_BASE)
/* GPIO controller (208 pins) */
#define GPIO_BASE (0x00680000U)
#define GPIO ((GPIO_V1_GPIOTypeDef *)GPIO_BASE)

/* IRQ numbers */
#define SW_IRQn (0U)
#define UART1_IRQn (1U)
#define UART2_IRQn (2U)
#define UART3_IRQn (3U)
#define UART4_IRQn (4U)
#define UART5_IRQn (5U)
#define WDT_IRQn (6U)
#define TIMER1_IRQn (7U)
#define TIMER2_IRQn (8U)
#define TIMER3_IRQn (9U)
#define TIMER4_IRQn (10U)
#define TIMER5_IRQn (11U)
#define GPIO_IRQn (12U)
#define I2C_IRQn (13U)
#define ARM_IRQn (14U)
#define DMA_IRQn (15U)

#endif /* ASPEED_AST2400_H */
